name: Backend CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Deploy to EC2
        run: scp -i C:\Users\Ayush\Downloads\devops.frontend.pem -r  ec2-user@ec2-13-211-202-104.ap-southeast-2.compute.amazonaws.com/backend/node


